fargo/urls.py
# fargo - document box
# Copyright (C) 2016-2019  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

from .fargo.api_views import push_document, recent_documents
from .fargo.views import (
    delete,
    download,
    edit,
    home,
    json,
    jsonp,
    login,
    logout,
    pick,
    pick_list,
    remote_download,
    thumbnail,
    upload,
)

urlpatterns = [
    path('', home, name='home'),
    path('pick/', pick_list, name='list_to_pick'),
    path('jsonp/', jsonp, name='jsonp'),
    path('json/', json, name='json'),
    path('<int:pk>/edit/', edit, name='edit'),
    path('<int:pk>/delete/', delete, name='delete'),
    path('<int:pk>/pick/', pick, name='pick'),
    re_path(r'^(?P<pk>\d+)/download/(?P<filename>[^/]*)$', download, name='download'),
    re_path(r'^(?P<pk>\d+)/thumbnail/(?P<filename>[^/]*)$', thumbnail, name='thumbnail'),
    path('upload/', upload, name='upload'),
    re_path(r'^remote-download/(?P<filename>[^/]*)$', remote_download, name='remote_download'),
    re_path(r'^admin/', admin.site.urls),
    path('login/', login, name='auth_login'),
    path('logout/', logout, name='auth_logout'),
    path('api/documents/push/', push_document, name='fargo-api-push-document'),
    path('api/documents/recently-added/', recent_documents),
]

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if 'mellon' in settings.INSTALLED_APPS:
    urlpatterns.append(path('accounts/mellon/', include('mellon.urls')))

fargo/fargo/models.py
# fargo - document box
# Copyright (C) 2016-2019  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import base64
import hashlib
import os
import re
from urllib.parse import quote

from django.conf import settings
from django.core.files.storage import default_storage
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse
from django.utils.html import format_html
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from sorl.thumbnail import delete, get_thumbnail
from sorl.thumbnail.conf import settings as thumbnail_settings

from . import managers, utils


def slug_truncate(label, length=256):
    slug = slugify(label)
    if len(slug) < length:
        return slug
    return slug[: length - 5] + '-%4s' % hashlib.md5(label.encode()).hexdigest()[:4]


class Origin(models.Model):
    label = models.TextField(_('Label'))
    slug = models.SlugField(_('Slug'), max_length=256)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slug_truncate(self.label)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.label


class UserDocument(models.Model):
    '''Document uploaded by an user or an agent'''

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('user'),
        related_name='user_documents',
        on_delete=models.CASCADE,
    )
    document = models.ForeignKey(
        'Document', related_name='user_documents', verbose_name=_('document'), on_delete=models.CASCADE
    )
    filename = models.CharField(verbose_name=_('filename'), max_length=512)
    created = models.DateTimeField(verbose_name=_('creation date'), auto_now_add=True)
    origin = models.ForeignKey(Origin, verbose_name=_('origin'), null=True, on_delete=models.CASCADE)
    deletable_by_user = models.BooleanField(verbose_name=_('deletable by user'), default=True)
    title = models.CharField(verbose_name=_('title'), max_length=200, blank=True)
    description = models.TextField(verbose_name=_('description'), blank=True)
    expiration_date = models.DateField(verbose_name=_('expiration date'), blank=True, null=True)

    class Meta:
        verbose_name = _('user document')
        verbose_name_plural = _('user documents')
        ordering = ('-created', 'user')
        unique_together = ('user', 'filename', 'document', 'origin', 'deletable_by_user')

    @property
    def filename_encoded(self):
        return quote(self.filename, safe='')

    def __str__(self):
        return self.title or self.filename

    def get_download_url(self):
        return reverse('download', kwargs={'pk': self.id, 'filename': self.filename_encoded})

    @property
    def thumbnail_image(self):
        thumbnail = self.document.thumbnail
        if not thumbnail:
            return ''
        src = reverse('thumbnail', kwargs={'pk': self.id, 'filename': self.filename_encoded})
        return {'src': src, 'width': thumbnail.width, 'height': thumbnail.height}

    @property
    def css_classes(self):
        if not self.document.mime_type:
            return ''
        return 'mime-%s mime-%s' % (
            self.document.mime_type.split('/')[0],
            re.sub(r'[/\.+-]', '-', self.document.mime_type),
        )


class Document(models.Model):
    '''Content indexed documents'''

    content_hash = models.CharField(primary_key=True, max_length=128, verbose_name=_('content hash'))
    content = models.FileField(upload_to='uploads/', max_length=300, verbose_name=_('file'))
    mime_type = models.CharField(max_length=256, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    objects = managers.DocumentManager()

    def save(self, *args, **kwargs):
        '''Create content_hash if new'''
        if not self.content_hash:
            self.content_hash = utils.sha256_of_file(self.content)
        if not self.mime_type:
            self.mime_type = utils.get_mime_type(self.content) or ''
        if self.content.name and len(self.content.name) > 200:
            file_root, file_ext = os.path.splitext(self.content.name)
            file_root, file_ext = file_root[:150], file_ext[:50]
            self.content.name = file_root + file_ext
        super().save(*args, **kwargs)

    @property
    def thumbnail(self):
        if not (self.mime_type.startswith('image/') or self.mime_type == 'application/pdf'):
            return None
        try:
            thumbnail = get_thumbnail(self.content, '200x200')
        except Exception:  # sorl-thumbnail can crash in unexpected ways
            return None
        try:
            # check file exists and is readable
            default_storage.open(thumbnail.name)
            return thumbnail
        except OSError:
            pass
        return None

    @property
    def thumbnail_data_url(self):
        thumbnail = self.thumbnail
        if not thumbnail:
            return ''

        mime_type = 'image/' + thumbnail_settings.THUMBNAIL_FORMAT.lower()
        return 'data:%s;base64,%s' % (mime_type, base64.b64encode(thumbnail.read()))

    @property
    def thumbnail_img_tag(self):
        thumbnail = self.thumbnail
        if not thumbnail:
            return ''

        return format_html(
            '<img width="{}" height="{}" src="{}"/>',
            thumbnail.width,
            thumbnail.height,
            self.thumbnail_data_url,
        )

    @property
    def thumbnail_image(self):
        thumbnail = self.thumbnail
        if not thumbnail:
            return ''
        return {'src': self.thumbnail_data_url, 'width': thumbnail.width, 'height': thumbnail.height}

    def __unicode__(self):
        return '%s %s' % (os.path.basename(self.content.name), self.content_hash[:6])

    class Meta:
        verbose_name = _('document')
        verbose_name_plural = _('documents')
        ordering = ('creation_date',)


@receiver(post_delete, sender=Document)
def delete_file(sender, instance, **kwargs):
    if instance.content:
        if os.path.isfile(instance.content.path):
            os.remove(instance.content.path)
    delete(instance.content)

fargo/fargo/forms.py
# fargo - document box
# Copyright (C) 2016-2019  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os

from django import forms
from django.conf import settings
from django.template.defaultfilters import filesizeformat
from django.utils.translation import gettext_lazy as _

from . import models


class UploadForm(forms.ModelForm):
    content = forms.FileField(label=_('file'), max_length=512)

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if content:
            if content.size > settings.FARGO_MAX_DOCUMENT_SIZE:
                raise forms.ValidationError(
                    _('Uploaded file is too big (limit is %s)')
                    % filesizeformat(settings.FARGO_MAX_DOCUMENT_SIZE)
                )
            if settings.FARGO_FORBIDDEN_EXTENSIONS:
                ext = os.path.splitext(content.name)[-1]
                if ext in settings.FARGO_FORBIDDEN_EXTENSIONS:
                    raise forms.ValidationError(_('Uploaded file is not allowed.'))
        return content

    def clean(self):
        content = self.cleaned_data.get('content')
        if content:
            if (
                models.Document.objects.used_space(self.instance.user) + content.size
                > settings.FARGO_MAX_DOCUMENT_BOX_SIZE
            ):
                raise forms.ValidationError(
                    _('Your document box is full (limit is %s)') % settings.FARGO_MAX_DOCUMENT_BOX_SIZE
                )
        return self.cleaned_data

    def save(self, *args, **kwargs):
        self.instance.filename = self.files['content'].name[:512]
        self.instance.document = models.Document.objects.get_by_file(self.files['content'])
        return super().save(*args, **kwargs)

    class Meta:
        model = models.UserDocument
        fields = []


class EditForm(forms.ModelForm):
    class Meta:
        model = models.UserDocument
        fields = ['title', 'description', 'expiration_date']
        widgets = {'expiration_date': forms.TextInput(attrs={'type': 'date'})}

fargo/templates/fargo/base.html
{% extends "gadjo/base.html" %}
{% load i18n static gadjo %}
{% block page-title %}Fargo{% endblock %}
{% block site-title %}Fargo{% endblock %}
{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "fargo/css/style.css" %}" />
{% endblock %}

{% block logout-url %}{% url "auth_logout" %}{% endblock %}

{% block content %}
{% endblock %}

fargo/templates/fargo/base_iframe.html
{% load gadjo static %}<!DOCTYPE html>
<html>
  <head>
    <script src="{% xstatic 'jquery' 'jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static "fargo/css/style.css" %}" />
    {% block extra_head %}
    {% endblock %}
  </head>
  <body class="{% block bodyclasses %}{% endblock %}">
    {% block content %}
    {% endblock %}
  </body>
</html>

fargo/templates/fargo/home.html
{% extends "fargo/base.html" %}
{% load render_table from django_tables2 %}
{% load gadjo i18n static %}

{% block content %}
  <script src="{% xstatic 'jquery-ui' 'jquery-ui.min.js' %}"></script>
  <script src="{% static "js/gadjo.js" %}"></script>

  <script>
    $(function () {
      $('tbody').on("click", "tr", function (event) {
        var $target = $(event.target)
        if ($target.is('a')) {
          /* let it be */
          return true;
        }
        if (! $target.is('tr')) {
          $target = $target.parents('tr');
        }
        var url = $target.data('url');
        if (url) {
          window.location.href = url;
        }
      });
      $('#send-file input[type=file]').on('change', function() {
        $('#id_content input[type=file]').change();
      });
      $('#id_content').on('change', function() {
        var fileSize = this.files[0].size;
        if (fileSize > {{ max_document_size  }}) {
          $('.invalid-file-error').show();
        }
        else {
          $('#send-file input[type=submit]').click();
        }
      });
      $('#send-file button').on('click', function() {
        $('#send-file input[type=file]').click();
        return false;
      });
    })
  </script>

  <div class="cell">
    <h2>{% if site_title %}{{ site_title }}{% else %}{% trans "Portfolio" %}{% endif %}</h2>
    <div id="user-files">
      {% render_table table "fargo/table.html" %}

      {% if full %}
        <div class="infonotice">
          <p>
            {% blocktrans count max_documents_per_user=max_documents_per_user trimmed %}
              The limit of {{ max_documents_per_user }} document per user is reached.
              You cannot add any more documents.
            {% plural %}
              The limit of {{ max_documents_per_user }} documents per user is reached.
              You cannot add any more documents.
            {% endblocktrans %}
          </p>
        </div>
      {% else %}
        <form id="send-file" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.non_field_errors }}
          {{ form.content.errors }}
          <div style="display: none">
            {{ form.as_p  }}
            <input type="submit" name="submit" value="Upload">
          </div>
          <div class="invalid-file-error" style="display: none">
            <p>
              {% blocktrans with max_size_mb=max_document_size|filesizeformat %}
                Error: an uploaded document can't exceed {{ max_size_mb }}.
              {% endblocktrans %}
            </p>
            <p>{% trans "Please try again with a smaller document." %}</p>
          </div>
          <button>{% trans "Upload a new document" %}</button>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

fargo/templates/fargo/pick.html
{% extends "fargo/base_iframe.html" %}
{% load render_table from django_tables2 %}
{% load i18n %}

{% block bodyclasses %}fargo-popup fargo-pick-popup{% endblock %}

{% block content %}
  {% render_table table "fargo/pick_table.html" %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.content.errors }}
    <div style="display: none">
      {{ form.as_p  }}
    </div>
  </form>
  <script type="text/javascript">
    $(function() {
      $('table').on('click', 'tbody tr', function() {
        $(this).find('form').submit();
      });
    });
  </script>
{% endblock %}

fargo/templates/fargo/pick_table.html
{% extends "fargo/table.html" %}
{% load django_tables2 i18n %}

{% block action-column %}
  <form method="post" action="{% url 'pick' pk=row.record.pk %}{% querystring %}">
    {% csrf_token %}
    <button class="pick-button">{% trans "Pick" %}</button>
  </form>
{% endblock %}

fargo/templates/fargo/table.html
{% extends "django_tables2/table.html" %}
{% load django_tables2 %}
{% load i18n %}

{% block table.thead %}
  <thead>
    <tr>
      <th class="orderable sortable title"><a href="?sort=title">{% trans "Title" %}</a></th>
      {% for column in table.columns %}
        {% if column.orderable %}
          <th {{ column.attrs.th.as_html }}>
            <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
          </th>
        {% else %}
          <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
        {% endif %}
      {% endfor %}
      <th class="desktop-only"></th>
      <th class="action-column"></th>
    </tr>
  </thead>
{% endblock table.thead %}

{% block table.tbody.row %}
  <tr class="{{ forloop.counter|divisibleby:2|yesno:"even,odd" }} {{row.record.css_classes}}"
      data-url="{{row.record.get_download_url}}"
  > {# avoid cycle for Django 1.2-1.6 compatibility #}
    <td class="title">
      {{ row.record }}
    </td>
    {% for column, cell in row.items %}
      <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
    {% endfor %}
    {% with thumbnail=row.record.thumbnail_image %}
      <td class="thumbnail desktop-only" rowspan={{ row.record.description|yesno:"2,1" }}>
        {% if thumbnail %}
          <img src="{{ thumbnail.src }}" height="{{ thumbnail.height }}" width="{{ thumbnail.width }}"/>
        {% endif %}
      </td>
    {% endwith %}
    <td class="action-column" rowspan={{ row.record.description|yesno:"2,1" }}>
      {% block action-column %}
        {% if table.context.include_edit_link or include_edit_link %}<!-- dj11 compatibility -->
          <a class="icon-edit" rel="popup" data-selector="#edit-form" href="{% url 'edit' pk=row.record.pk %}"></a>
        {% endif %}
        {% if row.record.deletable_by_user %}
          <a class="icon-remove" rel="popup" data-selector="#delete-form" href="{% url 'delete' pk=row.record.pk %}"></a>
        {% endif %}
      {% endblock %}
    </td>
  </tr>
  {% if row.record.description %}
    <tr class="{{ forloop.counter|divisibleby:2|yesno:"even,odd" }} description-row">
      <td class="description" colspan={{table.columns|length|add:"1"}}>{{row.record.description}}</td>
    </tr>
  {% endif %}
{% endblock table.tbody.row %}

{% block table.tbody.empty_text %}
  <tr class="empty"><td colspan="{{ table.columns|length|add:3 }}">{{ table.empty_text }}</td></tr>
{% endblock %}

{% block pagination.cardinality %}
{% endblock %}

fargo/templates/fargo/upload.html
{% extends "fargo/base.html" %}
{% load i18n %}


{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p  }}
    <button name="submit">{% trans "Upload" %}</button>
    <button name="cancel">{% trans "Cancel" %}</button>
  </form>
{% endblock %}

fargo/templates/fargo/userdocument_confirm_delete.html
{% extends "fargo/base.html" %}
{% load i18n %}

{% block content %}
  <form method="post" id="delete-form">
    {% csrf_token %}
    <p>
      {% blocktrans %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}
    </p>
    <div class="buttons">
      <button class="delete-button">{% trans 'Delete' %}</button>
      <a class="cancel" href="{% url 'home' %}">{% trans 'Cancel' %}</a>
    </div>
  </form>
{% endblock %}

fargo/templates/fargo/userdocument_form.html
{% extends "fargo/base.html" %}
{% load i18n %}

{% block content %}
  <div id="appbar">
    <h2>{% trans "Edit" %}</h2>
  </div>

  <form action="{% url 'edit' pk=object.pk %}" method="post" id="edit-form">
    {% csrf_token %}
    {{form.as_p}}
    <div class="buttons">
      <button class="submit-button">{% trans "Save" %}</button>
      <a class="cancel" href="{% url 'home' %}">{% trans 'Cancel' %}</a>
    </div>
  </form>
{% endblock %}

fargo/templates/fargo/validation.html
{% extends "fargo/base_iframe.html" %}
{% load i18n gadjo static %}

{% block extra_head %}
  <link rel="stylesheet" type="text/css" media="all"
        href="{% xstatic 'jquery-ui' 'themes/smoothness/jquery-ui.min.css' %}"/>
  <script src="{% xstatic 'jquery-ui' 'jquery-ui.min.js' %}"></script>
  <script src="{% static "fargo/js/datepicker-fr.js" %}"></script>
  <script src="{% static 'fargo/js/fargo.js' %}"></script>
{% endblock %}

{% block bodyclasses %}fargo-popup fargo-pick-popup{% endblock %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p  }}
    <div class="buttons">
      <button name="submit">{% trans "Validate" %}</button>
      <button name="cancel">{% trans "Cancel" %}</button>
    </div>
  </form>
  <script>
    $('#id_start, #id_end').datepicker($.datepicker.regional["fr"]);
  </script>
{% endblock %}